import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useAuth } from "../context/auth";
import styles from "../styles/Home.module.css";

export default function Home() {
  const { user } = useAuth();
  return (
    <div className={styles.container}>
      <Link href="/login">認証ページへ</Link>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <p>{user?.name}</p>
      </main>
    </div>
  );
}
